version: '3'
services:
  homeassistant:
    container_name: hass
    image: homeassistant/home-assistant
    volumes:
      - ./hass_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2
    network_mode: host
    user: "${PUID}:${PGID}"
    depends_on:
      - mosquitto
  environment:
      - DISABLE_JEMALLOC: true
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    restart: unless-stopped
    user: "${PUID}:${PGID}"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    user: "${PUID}:${PGID}"
  hass-configurator:
    image: "causticlab/hass-configurator-docker:arm"
    container_name: hass-configurator
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    depends_on:
      - homeassistant
    volumes:
      - "./configurator-config:/config"
      - "./hass-config:/hass-config"
    user: "${PUID}:${PGID}"
  # mariadb:
  #   image: linuxserver/mariadb
  #   container_name: mariadb
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  #     MYSQL_DATABASE: ha_db
  #     MYSQL_USER: homeassistant
  #     MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
  #     PUID: 1000
  #     PGID: 1000
  #   volumes:
  #     - ./mariadb:/config
  #   ports:
  #     - "3306:3306"
